language: ruby
rvm:
  - 2.4
sudo: false

branches:
  only:
  - master
install:
  - bundle install --jobs=3 --retry=3 --deployment
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
  - bundle exec mdl ./ -r ~MD004 -i -g
  - bundle exec "rake test"
