name: Build and test with Rake

on: [push]

# env:
#   NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - uses: actions/cache@v1
      id: gem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --deployment

    - name: Lint
      run: |
        bundle exec mdl ./ -r ~MD004 -i -g

    - name: Build and test with Rake
      run: |
        bundle exec "rake test"

  validate-files:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.22.1
      uses: actions/setup-node@v2
      with:
        node-version: "12.22.1"

    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      with:
        path: .scripts/doctor/node_modules
        key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json', '.github/workflows/build_and_test.yml') }}

    - name: Install dependencies
      run: |
        cd .scripts/doctor
        npm i
        sudo apt-get install -y md5

    - name: Validate
      run: |
        cd .scripts/doctor
        npm start
